#:property TargetFramework=net10.0
#:property UseArtifactsOutput=false
#:property TreatWarningsAsErrors=false
#:property EnforceCodeStyleInBuild=false
#:property PublishAot=false
#:property PackAsTool=false

using System.Text;
using System.Xml.Linq;

string root;
try
{
    root = Path.GetFullPath(args.Length > 0 ? args[0] : FindRepoRoot());
}
catch (Exception ex)
{
    Console.Error.WriteLine(ex.Message);
    return 1;
}

if (!Directory.Exists(root))
{
    Console.Error.WriteLine($"Repository root is invalid: {root}");
    return 1;
}

var outDir = Path.Combine(root, "docs", "diagrams");
Directory.CreateDirectory(outDir);

var packageVersions = LoadCentralPackageVersions(root);
var projects = DiscoverProjectPaths(root);

var projEdges = new HashSet<(string From, string To)>(new EdgeComparer());
var pkgEdges = new HashSet<(string Project, string Package, string? Version)>(new PkgEdgeComparer());

foreach (var (relPath, fullPath) in projects)
{
    var doc = XDocument.Load(fullPath);
    var projEl = doc.Root ?? throw new InvalidOperationException($"No root: {relPath}");

    foreach (var pr in projEl.Descendants("ProjectReference"))
    {
        var inc = pr.Attribute("Include")?.Value;
        if (string.IsNullOrWhiteSpace(inc))
            continue;
        var targetPath = Path.GetFullPath(Path.Combine(Path.GetDirectoryName(fullPath)!, inc));
        var targetRel = ToRepoRelative(root, targetPath).Replace('\\', '/');
        if (!projects.TryGetValue(targetRel, out _))
            continue;
        var fromName = Path.GetFileNameWithoutExtension(fullPath);
        var toName = Path.GetFileNameWithoutExtension(targetPath);
        projEdges.Add((fromName, toName));
    }

    foreach (var pkg in projEl.Descendants("PackageReference"))
    {
        var id = pkg.Attribute("Include")?.Value;
        if (string.IsNullOrWhiteSpace(id))
            continue;
        var ver = packageVersions.GetValueOrDefault(id);
        var projName = Path.GetFileNameWithoutExtension(fullPath);
        pkgEdges.Add((projName, id, ver));
    }
}

WriteProjectReferencesMd(Path.Combine(outDir, "project-references.md"), projEdges);
WriteNugetReferencesMd(Path.Combine(outDir, "nuget-references.md"), pkgEdges);
WriteLayerMapMd(Path.Combine(outDir, "layer-map.md"));

return 0;

static Dictionary<string, string> LoadCentralPackageVersions(string root)
{
    var path = Path.Combine(root, "Directory.Packages.props");
    if (!File.Exists(path))
        return new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

    var doc = XDocument.Load(path);
    var map = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
    foreach (var el in doc.Descendants("PackageVersion"))
    {
        var id = el.Attribute("Include")?.Value;
        var ver = el.Attribute("Version")?.Value;
        if (id is not null && ver is not null)
            map[id] = ver;
    }

    return map;
}

static Dictionary<string, string> DiscoverProjectPaths(string root)
{
    var map = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
    foreach (var segment in new[] { "src", "tests" })
    {
        var dir = Path.Combine(root, segment);
        if (!Directory.Exists(dir))
            continue;
        foreach (var full in Directory.EnumerateFiles(dir, "*.csproj", SearchOption.AllDirectories))
        {
            var rel = ToRepoRelative(root, full).Replace('\\', '/');
            map[rel] = full;
        }
    }

    return map;
}

static string ToRepoRelative(string root, string fullPath) =>
    Path.GetRelativePath(root, fullPath);

static void WriteProjectReferencesMd(string path, IReadOnlySet<(string From, string To)> edges)
{
    var sb = new StringBuilder();
    sb.AppendLine("# Project reference graph");
    sb.AppendLine();
    sb.AppendLine("<!-- Generated by `.githooks/GenerateDocDiagrams.cs`. Do not edit by hand. -->");
    sb.AppendLine();
    sb.AppendLine("All `ProjectReference` edges between projects under `src/` and `tests/`.");
    sb.AppendLine();
    sb.AppendLine("```mermaid");
    sb.AppendLine("flowchart TD");
    foreach (var (a, b) in edges.OrderBy(e => e.From, StringComparer.OrdinalIgnoreCase).ThenBy(e => e.To, StringComparer.OrdinalIgnoreCase))
        sb.AppendLine($"  {MermaidId(a)}[\"{EscapeMermaidLabel(a)}\"] --> {MermaidId(b)}[\"{EscapeMermaidLabel(b)}\"]");
    if (edges.Count == 0)
        sb.AppendLine("  empty[\"No project references discovered\"]");
    sb.AppendLine("```");
    sb.AppendLine();
    File.WriteAllText(path, sb.ToString().ReplaceLineEndings("\n"), new UTF8Encoding(false));
}

static void WriteNugetReferencesMd(string path, IReadOnlySet<(string Project, string Package, string? Version)> edges)
{
    var sb = new StringBuilder();
    sb.AppendLine("# NuGet package references");
    sb.AppendLine();
    sb.AppendLine("<!-- Generated by `.githooks/GenerateDocDiagrams.cs`. Do not edit by hand. -->");
    sb.AppendLine();
    sb.AppendLine("Direct `PackageReference` items per project, with versions from `Directory.Packages.props` where applicable.");
    sb.AppendLine();
    sb.AppendLine("```mermaid");
    sb.AppendLine("flowchart LR");
    foreach (var (proj, pkg, ver) in edges.OrderBy(e => e.Project, StringComparer.OrdinalIgnoreCase)
                 .ThenBy(e => e.Package, StringComparer.OrdinalIgnoreCase))
    {
        var label = ver is null ? pkg : $"{pkg} v{ver}";
        sb.AppendLine($"  {MermaidId(proj)}[\"{EscapeMermaidLabel(proj)}\"] --> {MermaidId($"pkg_{pkg}")}[\"{EscapeMermaidLabel(label)}\"]");
    }

    if (edges.Count == 0)
        sb.AppendLine("  empty[\"No package references discovered\"]");
    sb.AppendLine("```");
    sb.AppendLine();
    File.WriteAllText(path, sb.ToString().ReplaceLineEndings("\n"), new UTF8Encoding(false));
}

static void WriteLayerMapMd(string path)
{
    // Teaching-oriented layer view aligned with AGENTS.md dependency direction.
    const string content = """
        # Layer map (intent)

        <!-- Generated by `.githooks/GenerateDocDiagrams.cs`. Do not edit by hand. -->

        High-level dependency direction (hosts inward). This is a conceptual map, not an exact project graph.

        ```mermaid
        flowchart TB
          subgraph hosts["Hosts"]
            Player["RoboSharp.Player"]
            Studio["RoboSharp.Studio"]
            Web["RoboSharp.Web"]
          end
          Hosting["RoboSharp.Hosting"]
          Application["RoboSharp.Application"]
          Toolchain["RoboSharp.Toolchain"]
          subgraph core["Compiler / runtime stack"]
            Language["RoboSharp.Language"]
            Semantics["RoboSharp.Semantics"]
            IL["RoboSharp.IL"]
            Runtime["RoboSharp.Runtime"]
            World["RoboSharp.World"]
            IO["RoboSharp.IO"]
            Workspaces["RoboSharp.Workspaces"]
          end
          hosts --> Hosting
          Hosting --> Application
          Application --> Toolchain
          Toolchain --> Language
          Toolchain --> Semantics
          Toolchain --> IL
          Toolchain --> Runtime
          Toolchain --> World
          Toolchain --> IO
          Toolchain --> Workspaces
          Semantics --> Language
          IL --> Semantics
          Runtime --> IL
          Runtime --> World
          Workspaces --> IO
        ```

        """;
    File.WriteAllText(path, content.ReplaceLineEndings("\n"), new UTF8Encoding(false));
}

static string MermaidId(string name)
{
    var sb = new StringBuilder(name.Length + 8);
    foreach (var c in name)
    {
        if (char.IsLetterOrDigit(c))
            sb.Append(c);
        else
            sb.Append('_');
    }

    if (sb.Length > 0 && char.IsDigit(sb[0]))
        sb.Insert(0, 'P');
    return sb.Length == 0 ? "node" : sb.ToString();
}

static string EscapeMermaidLabel(string text) =>
    text.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);

static string FindRepoRoot()
{
    var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
    while (dir is not null)
    {
        if (File.Exists(Path.Combine(dir.FullName, "RoboSharp.slnx")))
            return dir.FullName;
        dir = dir.Parent;
    }

    throw new InvalidOperationException(
        "Could not locate RoboSharp.slnx; pass the repository root as the first argument.");
}

file sealed class EdgeComparer : IEqualityComparer<(string From, string To)>
{
    public bool Equals((string From, string To) x, (string From, string To) y) =>
        string.Equals(x.From, y.From, StringComparison.OrdinalIgnoreCase)
        && string.Equals(x.To, y.To, StringComparison.OrdinalIgnoreCase);

    public int GetHashCode((string From, string To) obj) =>
        HashCode.Combine(
            StringComparer.OrdinalIgnoreCase.GetHashCode(obj.From),
            StringComparer.OrdinalIgnoreCase.GetHashCode(obj.To));
}

file sealed class PkgEdgeComparer : IEqualityComparer<(string Project, string Package, string? Version)>
{
    public bool Equals((string Project, string Package, string? Version) x, (string Project, string Package, string? Version) y) =>
        string.Equals(x.Project, y.Project, StringComparison.OrdinalIgnoreCase)
        && string.Equals(x.Package, y.Package, StringComparison.OrdinalIgnoreCase)
        && x.Version == y.Version;

    public int GetHashCode((string Project, string Package, string? Version) obj) =>
        HashCode.Combine(
            StringComparer.OrdinalIgnoreCase.GetHashCode(obj.Project),
            StringComparer.OrdinalIgnoreCase.GetHashCode(obj.Package),
            obj.Version?.GetHashCode(StringComparison.Ordinal) ?? 0);
}
